name: Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build_backend:
    name: Build Node Backend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: node-backend
    steps:
    
    - uses: actions/checkout@v3

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag sonar-node-backend:$(date +%s)
    
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      with:
        buildkitd-flags: --debug

    - name: ls
      run: |
          echo "Root Directory"
          pwd
          ls -1lta .

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: /home/runner/work/Sonar/Sonar/node-backend/
        file: Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/sonar-node-backend:latest
